version: '2'
services:
  appbuchladen:
    image: gerry1313/buchladentester:latest
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "32770:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASES=buchladen
      - MYSQL_MY_DATABASE=buchladen
      - MYSQL_HOST=localhost
      - MYSQL_PORT=32770
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
   


