version: '3.5'
services:
  appbuchladen:
    image: gerry1313/buchladentester:latest
    container_name: appbuchladen
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=buchladen
      - DATABASE_PORT=3306
    depends_on:
      - docker-mysql
  docker-mysql:
    image: mysql:latest
    container_name: docker-mysql
    volumes:
    - buchladen_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=buchladen
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
volumes:
  buchladen_volume:



